service:
    name: harness_guestbook
    identifier: harnessguestbook
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: guestbook
                    type: K8sManifest
                    spec:
                        apiVersion: v1
                        kind: Service
                        metadata:
                          name: guestbook-ui
                        spec:
                          ports:
                          - port: 80
                            targetPort: 80
                          selector:
                            app: guestbook-ui
    gitOpsEnabled: false
